// <auto-generated />
namespace Spectare.Classes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Changingtypeonfilmtype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changingtypeonfilmtype));
        
        string IMigrationMetadata.Id
        {
            get { return "201806111948257_Changing type on filmtype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
