// <auto-generated />
namespace Spectare.Classes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Сделалировно3кадраизфильма : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Сделалировно3кадраизфильма));
        
        string IMigrationMetadata.Id
        {
            get { return "201806131131028_Сделали ровно 3 кадра из фильма"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
